"""
Revision ID: 6945b9177290
Revises: 6a4b796b3f86
Create Date: 2025-09-07 21:06:03.313391

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6945b9177290"
down_revision: str | None = "6a4b796b3f86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("journal_entries", sa.Column("emotions", sa.JSON(), nullable=True))
    op.drop_index(op.f("ix_journal_entries_id"), table_name="journal_entries")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_journal_entries_id"), "journal_entries", ["id"], unique=False
    )
    op.drop_column("journal_entries", "emotions")
    # ### end Alembic commands ###
