"""
Revision ID: eebbac5e008f
Revises: 6945b9177290
Create Date: 2025-09-14 19:48:29.552472

"""

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "eebbac5e008f"
down_revision: str | None = "6945b9177290"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
