"""
Revision ID: 54f1db7abd12
Revises: eebbac5e008f
Create Date: 2025-09-14 20:23:48.252494

"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = "54f1db7abd12"
down_revision: str | None = "eebbac5e008f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_entries", sa.Column("embedding", VECTOR(dim=384), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journal_entries", "embedding")
    # ### end Alembic commands ###
