"""
Revision ID: bc2da9c34233
Revises: 54f1db7abd12
Create Date: 2025-09-20 15:43:30.935833

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc2da9c34233"
down_revision: str | None = "54f1db7abd12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_entries", sa.Column("keywords", sa.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journal_entries", "keywords")
    # ### end Alembic commands ###
